apiVersion: v1
kind: PersistentVolume
metadata:
  name: stor0-nfs-dms-dev
spec:
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.88.8
    path: "/mnt/rr1/kuber/dms_dev"
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stor0-nfs-dms
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: stor0-nfs-dms-dev
  resources:
    requests:
      storage: 10G
---
