version: '3'

services:
  documentation:
    build:
      context: ../api-specification
  mock:
    build:
      context: ../api-specification
  frontend-app:
    build:
      context: ../frontend
  backend-app:
    build:
      context: ../backend
  proxy:
    container_name: dms_proxy
    build:
      context: ../proxy
    depends_on:
      - mock
      - documentation
      - backend-app
      - frontend-app
    ports:
      - 80:80
